export const Services = [
  "Melvin Jones Repol",
  "Software engineering consulting",
  "Enterprise software development",
  "DevOps consulting services",
  "Scalable software solutions",
  "Custom software architecture",
  "Continuous integration and deployment (CI/CD)",
  "Software reliability engineering",
  "Secure software development",
  "Automated deployment pipelines",
  "Systems architecture consulting",
  "Professional software development for enterprises",
  "Consulting services for continuous delivery and automation",
  "Secure, scalable, and maintainable software solutions",
  "DevOps and cloud strategy for large organizations",
  "Software architecture best practices for enterprises",
  "Melvin Jones Repol software consulting",
  "Melvin Jones Repol consulting",
  "Melvin Jones Repol DevOps expert",
  "Melvin Jones enterprise software",
  "Melvin Jones software architect",
  "Android application development",
  "Mobile app development services",
  "Java programming services",
  "Kotlin Android development",
  "Cross-platform mobile development",
  "Cloud application development",
  "Serverless computing consulting",
  "RESTful API development",
  "Backend development services",
  "Frontend web development",
  "React and Angular development",
  "Progressive Web Apps (PWA)",
  "DevSecOps services",
  "Continuous delivery pipelines",
  "Continuous delivery pipelines",
  "Enterprise IT strategy",
  "Software performance optimization",
  "Debugging and troubleshooting services",
  "Android SDK expertise",
  "Mobile UX/UI design",
];
